CREATE TABLE projects (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id integer,
  client_id varchar(50),
  project_name varchar(50) NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE tasks (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id varchar(50),
  task_name varchar(50) NOT NULL,
  recorded_time integer DEFAULT 0,
  project_id integer NOT NULL,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON UPDATE CASCADE ON DELETE CASCADE,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);
