CREATE TABLE projects (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id INTEGER ,
  client_id varchar(50),
  project_name varchar(50) NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);
